/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export const Apartment = (props) => {
  const { nodes, materials } = useGLTF('/models/apartment.glb') as any;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BalconyWoodTables.geometry}
        material={materials.BalconyWood}
        scale={[0.63, 0.63, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HorizontalBalcony.geometry}
        material={materials.MetalBalcony}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.85}
      />
      <group scale={[0.59, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.WallBlack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.Building}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials.WallWhite}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CilindroMedio.geometry}
        material={materials.MetalBalcony}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <group scale={[0.53, 0.75, 0.75]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.MetalBalcony}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VerticalBalcony.geometry}
        material={materials.MetalBalcony}
      />
      <group position={[-0.26, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials.MetalBalcony}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/models/apartment.glb');
